apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: acndemo-lb
  name: acndemo-lb
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}
