apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: acndemo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: acndemo
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: acndemo
  name: acndemo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: acndemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: acndemo
    spec:
      containers:
      - image: gcr.io/knative-samples/knative-route-demo:blue
        name: acndemo
        ports:
        - containerPort: 8080
        resources: {}
status: {}
